name: Mirror to Bitbucket

on:
  push:
    branches: ["**"]
  delete:
    branches: ["**"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history required for mirror push

      - name: Push mirror to Bitbucket
        env:
          BITBUCKET_API_TOKEN: ${{ secrets.BITBUCKET_API_TOKEN }}
        run: |
          git remote add bitbucket \
            https://x-token-auth:${BITBUCKET_API_TOKEN}@bitbucket.org/boomii/boomi-exec-assistant.git
          git push bitbucket --mirror
